<?php echo $this->doctype(); ?>

<html lang="en">
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle('The SMILE Project')->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
	?>

	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $this->basePath() . '/img/favicon.png'))
		->prependStylesheet($this->basePath('css/style.css'))
		->prependStylesheet('https://fonts.googleapis.com/css?family=Roboto:400,500,700,400italic')
		->prependStylesheet('https://fonts.googleapis.com/icon?family=Material+Icons')
		->prependStylesheet($this->basePath('css/angular-common-libs.css')) ?>

	<!-- Scripts -->
	<?php echo $this->headScript()
		->prependFile($this->basePath('js/BackofficeClientMgmtCtrl.js'))
		->prependFile($this->basePath('js/BackofficeKbInfoCtrl.js'))
		->prependFile($this->basePath('js/BackofficeKbOpRiskCtrl.js'))
		->prependFile($this->basePath('js/BackofficeKbModelsCtrl.js'))
		->prependFile($this->basePath('js/BackofficeMainCtrl.js'))
		->prependFile($this->basePath('js/BackofficeLoginCtrl.js'))
		->prependFile($this->basePath('js/BackofficeAdminServerCtrl.js'))
		->prependFile($this->basePath('js/BackofficeAdminUsersCtrl.js'))
		->prependFile($this->basePath('js/TableHelperService.js'))
		->prependFile($this->basePath('js/ClientService.js'))
		->prependFile($this->basePath('js/AssetService.js'))
		->prependFile($this->basePath('js/ThreatService.js'))
		->prependFile($this->basePath('js/VulnService.js'))
		->prependFile($this->basePath('js/CategoryService.js'))
		->prependFile($this->basePath('js/TagService.js'))
		->prependFile($this->basePath('js/RiskService.js'))
		->prependFile($this->basePath('js/AmvService.js'))
		->prependFile($this->basePath('js/ObjlibService.js'))
		->prependFile($this->basePath('js/MeasureService.js'))
		->prependFile($this->basePath('js/ModelService.js'))
		->prependFile($this->basePath('js/UserService.js'))
		->prependFile($this->basePath('js/AdminServerService.js'))
		->prependFile($this->basePath('js/AdminUsersService.js'))
		->prependFile($this->basePath('js/ErrorService.js'))
		->prependFile($this->basePath('js/ConfigService.js'))
		->prependFile($this->basePath('js/BackofficeApp.js'))
		->prependFile($this->basePath('js/translations.js'))
		//->prependFile($this->basePath('js/app.min.js'))
		->prependFile($this->basePath('js/angular-common-libs.js')); ?>

</head>
<body ng-app="BackofficeApp" layout="column" flex>
<section layout="row" flex ui-view="main">
</section>

<?php echo $this->inlineScript() ?>

</body>
</html>

