<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>MONARC</title>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/png', 'href' => 'img/favicon.png'))
        ->prependStylesheet(('css/style.css'))
        ->prependStylesheet(('css/anr/anr.css'))
        ->prependStylesheet(('css/material-icons.css'))
        ->prependStylesheet(('css/angular-common-libs.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        // TODO: In Production mode, use app.min.js which is a minified version of everything below. It must be
        // generated using grunt concat/uglify task.
        // Global files
        ->appendFile(('js/angular-common-libs.js'))
        ->appendFile(('js/translations.js'))
        ->appendFile(('js/BackofficeApp.js'))
        ->appendFile(('js/ErrorService.js'))
        ->appendFile(('js/ConfigService.js'))
        // ANR module
        ->appendFile(('js/anr/AnrModule.js'))
        ->appendFile(('js/anr/AnrService.js'))
        ->appendFile(('js/anr/AnrLayoutCtrl.js'))
        ->appendFile(('js/anr/AnrObjectCtrl.js'))
        ->appendFile(('js/anr/AnrObjectInstanceCtrl.js'))
        ->appendFile(('js/anr/ObjlibService.js'))
        ->appendFile(('js/anr/ModelService.js'))
        ->appendFile(('js/anr/CreateObjlibDialogCtrl.js'))
        ->appendFile(('js/anr/TagService.js'))
        ->appendFile(('js/anr/AssetService.js'))
        ->appendFile(('js/anr/MassDeleteService.js'))
        ->appendFile(('js/anr/MeasureService.js'))
        ->appendFile(('js/anr/MetadataInstanceService.js'))
        ->appendFile(('js/anr/MeasureMeasureService.js'))
        ->appendFile(('js/anr/ThreatService.js'))
        ->appendFile(('js/anr/VulnService.js'))
        ->appendFile(('js/anr/RiskService.js'))
        ->appendFile(('js/anr/AmvService.js'))
        ->appendFile(('js/anr/CategoryService.js'))
        ->appendFile(('js/anr/ToolsAnrService.js'))
        ->appendFile(('js/anr/InstanceService.js'))
        ->appendFile(('js/anr/QuestionService.js'))
        ->appendFile(('js/anr/AnrObjectResource.js'))
        ->appendFile(('js/anr/SoaScaleCommentService.js'))

        //Tools
        ->appendFile(('js/anr/EditableDirective.js'))
        ->appendFile(('js/anr/DashNullFilter.js'))
        // Admin section
        ->appendFile(('js/admin/AdminLogsService.js'))
        ->appendFile(('js/admin/AdminServerService.js'))
        ->appendFile(('js/admin/AdminUsersService.js'))
        ->appendFile(('js/admin/BackofficeAdminLogsCtrl.js'))
        ->appendFile(('js/admin/BackofficeAdminServerCtrl.js'))
        ->appendFile(('js/admin/BackofficeAdminUsersCtrl.js'))
        // KB Info
        ->appendFile(('js/kb/info/BackofficeKbInfoCtrl.js'))
        ->appendFile(('js/anr/SOACategoryService.js'))
        ->appendFile(('js/anr/ReferentialService.js'))
        ->appendFile(('js/anr/ImportFileDialogCtrl.js'))
        // KB ROLF
        ->appendFile(('js/kb/rolf/BackofficeKbOpRiskCtrl.js'))
        // KB Models
        ->appendFile(('js/kb/models/BackofficeKbModelsCtrl.js'))
        // Other KB sections
        ->appendFile(('js/kb/BackofficeQuestionsCtrl.js'))
        ->appendFile(('js/kb/BackofficeAnalysisGuidesCtrl.js'))
        ->appendFile(('js/kb/BackofficeAnalysisGuidesItemsCtrl.js'))
        ->appendFile(('js/kb/BackofficeDeliveriesModelsCtrl.js'))
        ->appendFile(('js/kb/DeliveriesModelsService.js'))
        ->appendFile(('js/anr/GuideService.js'))
        // General sections
        ->appendFile(('js/BackofficeAccountCtrl.js'))
        ->appendFile(('js/BackofficeLoginCtrl.js'))
        ->appendFile(('js/BackofficePasswordForgottenCtrl.js'))
        ->appendFile(('js/BackofficeMainCtrl.js'))
        ->appendFile(('js/BackofficeClientMgmtCtrl.js'))
        ->appendFile(('js/ClientService.js'))
        ->appendFile(('js/UserService.js'))
        ->appendFile(('js/UserProfileService.js'))
        // Helpers
        ->appendFile(('js/TableHelperService.js'))
        ->appendFile(('js/anr/DownloadService.js'))
        // FO compatibility
        ->appendFile(('js/ClientRecommandationService.js')); ?>

</head>
<body ng-app="BackofficeApp" layout="column" flex>
<section layout="row" flex ui-view="main">
</section>

<?php echo $this->inlineScript() ?>

</body>
</html>
